replicaCount: 1
image:
  repository: ghcr.io/brubru-420/todo-api 
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
env:
  NODE_ENV: production
  PORT: "3000"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"